package com.dynodevv.relay.ui.theme

import androidx.compose.ui.graphics.Color

// Light theme — modern indigo & warm coral palette
val md_theme_light_primary = Color(0xFF4F46E5)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFE0E7FF)
val md_theme_light_onPrimaryContainer = Color(0xFF1E1B4B)
val md_theme_light_secondary = Color(0xFFEA580C)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFFFEDD5)
val md_theme_light_onSecondaryContainer = Color(0xFF431407)
val md_theme_light_tertiary = Color(0xFF0891B2)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFCFFAFE)
val md_theme_light_onTertiaryContainer = Color(0xFF164E63)
val md_theme_light_error = Color(0xFFDC2626)
val md_theme_light_errorContainer = Color(0xFFFEE2E2)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(0xFF7F1D1D)
val md_theme_light_background = Color(0xFFFAFAFA)
val md_theme_light_onBackground = Color(0xFF18181B)
val md_theme_light_surface = Color(0xFFFFFFFF)
val md_theme_light_onSurface = Color(0xFF18181B)
val md_theme_light_surfaceVariant = Color(0xFFF4F4F5)
val md_theme_light_onSurfaceVariant = Color(0xFF52525B)
val md_theme_light_outline = Color(0xFFA1A1AA)
val md_theme_light_inverseOnSurface = Color(0xFFF4F4F5)
val md_theme_light_inverseSurface = Color(0xFF27272A)
val md_theme_light_inversePrimary = Color(0xFFA5B4FC)
val md_theme_light_surfaceTint = Color(0xFF4F46E5)

// Dark theme — deep & vibrant
val md_theme_dark_primary = Color(0xFFA5B4FC)
val md_theme_dark_onPrimary = Color(0xFF312E81)
val md_theme_dark_primaryContainer = Color(0xFF4338CA)
val md_theme_dark_onPrimaryContainer = Color(0xFFE0E7FF)
val md_theme_dark_secondary = Color(0xFFFDBA74)
val md_theme_dark_onSecondary = Color(0xFF7C2D12)
val md_theme_dark_secondaryContainer = Color(0xFF9A3412)
val md_theme_dark_onSecondaryContainer = Color(0xFFFFEDD5)
val md_theme_dark_tertiary = Color(0xFF67E8F9)
val md_theme_dark_onTertiary = Color(0xFF155E75)
val md_theme_dark_tertiaryContainer = Color(0xFF0E7490)
val md_theme_dark_onTertiaryContainer = Color(0xFFCFFAFE)
val md_theme_dark_error = Color(0xFFFCA5A5)
val md_theme_dark_errorContainer = Color(0xFF991B1B)
val md_theme_dark_onError = Color(0xFF450A0A)
val md_theme_dark_onErrorContainer = Color(0xFFFEE2E2)
val md_theme_dark_background = Color(0xFF09090B)
val md_theme_dark_onBackground = Color(0xFFE4E4E7)
val md_theme_dark_surface = Color(0xFF18181B)
val md_theme_dark_onSurface = Color(0xFFE4E4E7)
val md_theme_dark_surfaceVariant = Color(0xFF27272A)
val md_theme_dark_onSurfaceVariant = Color(0xFFA1A1AA)
val md_theme_dark_outline = Color(0xFF52525B)
val md_theme_dark_inverseOnSurface = Color(0xFF27272A)
val md_theme_dark_inverseSurface = Color(0xFFE4E4E7)
val md_theme_dark_inversePrimary = Color(0xFF4F46E5)
val md_theme_dark_surfaceTint = Color(0xFFA5B4FC)
